In [9]:
numbers = open("Numbers", "w")
for i in range (4):
    input_number = input("Enter a number: ")
    numbers.write(str(input_number))
    if i == 3:
        " "
    else:
        numbers.write(", ")
    i=i+1
numbers.close()

In [1]:
input_mark=int(input("Hello, to start enter score: "))
target_grade = (input("Please enter your target grade "))

def grade_mark(input_mark):
    if target_grade == "A" and input_mark > 92 and input_mark <=100 :
        output = print("Congratulations on meeting your target grade A with the score of", input_mark) 
    elif target_grade == "A" and input_mark < 92:
        output = print("Unfortunatly you did not acheive your target grade A with your score of", input_mark, " keep pushing yourself to meet your target grade")
    elif target_grade == "A-" and input_mark > 89 and input_mark <= 92:
        output = print("Congratulations on meeting your target grade A- with the score of", input_mark) 
    elif target_grade == "A-" and input_mark > 92 and input_mark <=100:
        output= print("Congratulations for exceeding your target grade A- with the score of", input_mark)
    elif target_grade == "A-" and input_mark < 89:
        output = print("Unfortunatly you did not acheive your target grade A- with your score of", input_mark, " keep pushing yourself to meet your target grade")
    elif target_grade== "B+" and input_mark > 86 and input_mark <= 89:
        output = print("Congratulations on meeting your target grade B+ with the score of", input_mark)
    elif target_grade ==  "B+" and input_mark > 89:
        output = print("Congratulations on exceeding you target grade of B+ with a score of", input_mark)
    elif target_grade == "B+" and input_mark <= 86:
        output = print("Unfortunately you did not acheive your target grade of B+ with a score of", input_mark, " keep pushing yourself to meet your target grade")
    elif target_grade == "B" and input_mark > 82 and input_mark <= 86:
        output = print("Congratulation on meeting your target grade of B with a score of", input_mark)
    elif target_grade == "B" and input_mark > 86:
        output = print("Congratulation on exceeding your target grade of B with a score of", input_mark)
    elif target_grade == "B" and input_mark < 82:
        output = print("Unfortunately you did not acheive your target grade of B with a score of", input_mark, " keep pushing yourself to meet your target grade")
    elif target_grade == "B-" and input_mark > 79 and input_mark <= 82:
        output = print("Congatulations on meeting your target grade of B- with a score of", input_mark)
    elif target_grade == "B-" and input_mark > 82:
        output = print("Congratulations on exceeding your target grade of B- with a score of", input_mark)
    elif target_grade =="B-" and target_grade < 79:
        output = print("Unfortunately  you did not acheive your target grade of B- with a score of", input_mark, " keep pushing yourelf to meet yout target grade")
    elif target_grade == "C+" and input_mark > 76 and input_mark <= 79:
        output = print("Congratulations on meeting your target grade of C+ with a score of", input_mark)
    elif target_grade == "C+" and input_mark > 79:
        output = print("Congratulations on exceeding your target grade of C+ with a score of", input_mark)
    elif target_grade == "C+" and input_mark < 76:
        output = print("Unfortunately you did not acheive your target grade of C+ with a score of", input_mark, " keep pushing yourslef to meet your target grade")
    elif target_grade == "C" and input_mark > 72 and input_mark <= 76:
        output = print("Congratulations on meeting your target grade of C with a score of", input_mark)
    elif target_grade == "C" and input_mark > 76:
        output = print("Congratulations on exceeding your target grade of C with a score of", input_mark)
    elif target_grade == "C" and target_grade < 72:
        output= print("Unfortunately you did not acheieve your target grade of C with a score of", input_mark, " keep pushing yourself to meet your target grade")
    elif target_grade == "C-" and input_mark > 69 and input_mark <= 72:
        output = print("Congratulations on meeting your target grade of C- with a score of", input_mark)
    elif target_grade == "C-" and input_mark < 69:
        output = print("Unfortunately you did not acheive your target grade of C- with a score of", input_mark, " keep pushing yourself to meet your target grade")
    elif target_grade == "D+" and input_mark > 66 and input_mark <= 69:
        output = print("Congratulations on meeting your target grade with a score of D+", input_mark)
    elif target_grade == "D+" and input_mark > 69:
        output = print("Congratulations on exceeding your target grade of D+ with a score of", input_mark)
    elif target_grade == "D+" and input_mark < 66:
        output = print("Unfortunately you did not acheive your target grade of D+ with a score of", input_mark, " keep pushing yourself to meet your target grade")
    elif target_grade == "D" and input_mark > 62 and input_mark <= 66:
        output = print("Congratulations on meeting your target grade of D with a score of", input_mark)
    elif target_grade == "D" and input_mark > 66:
        output = print("Congratulations on exceeding your target grade of D with a score of", input_mark)
    elif target_grade == "D" and input_mark < 62:
        output = print("Unfortunately you did not acheive your target grade of D with a score of", input_mark, " keep pushing yourself to meet our target grade")
    elif target_grade == "D-" and input_mark > 59 and input_mark <= 62:
        output = print("Congratulations on meeting your target grade of D- with a score of", input_mark)
    elif target_grade == "D-" and input_mark > 62:
        output = print("Congratulations on exceeding your target grade of D- with a score of", input_mark)
    elif target_grade == "D-" and input_mark < 59:
        output = print("Unfortunately you did not chaeive your target grade of D- with a score of", input_mark, " keep pushnig yourself to meet target grade")
    elif target_grade == "F" and input_mark < 59:
        output = print("You acheived your target grade of F with a score of", input_mark)
    elif target_grade == "F" and input_mark >59:
        output = print ("Good work, you exceeded your target grade of F with a score of", input_mark)
    else:
        output = print("Enter a score from 0 to 100 and a target grade of A, A-, B+, B, B-, C+, C, C-, D+, D, D-, F")
    return output
grade_mark(input_mark)


Unfortunately you did not acheive your target grade of B with a score of 78  keep pushing yourself to meet your target grade


In [5]:
import numpy as np

list = np.arange(10)

print(list)

[0 1 2 3 4 5 6 7 8 9]


In [17]:
booleanTrue = np.ones(9).reshape(3,3)
print(booleanTrue)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [37]:
alist = np.arange(1,11)
for i in range(len(alist)):
    if alist[i] % 2 !=0:
        print(alist[i])
    else:
        " "

1
3
5
7
9


In [39]:

for i in range(len(alist)):
    if alist[i] % 2 !=0:
        print("-1")
    else:
        print(alist[i])

-1
2
-1
4
-1
6
-1
8
-1
10


In [44]:
reshaped = np.arange(12).reshape(2,6)
print(reshaped)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]


In [67]:
a = np.arange(1,10).reshape(3,3)
b = np.arange(10,19).reshape(3,3)
abstack = np.stack([a,b])
abdot = np.dot(a,b)
absum0 = np.sum(abdot,axis=0)
absum1 = np.sum(abdot, axis=1)
print(abstack)
print(absum0)
print(absum1)


[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]]
[603 648 693]
[ 270  648 1026]


In [139]:
x = np.arange(1,4)
xsequence=[]
y = np.repeat(x,3)
for i in range (len(x)):
    xsequence.append(x)
print([y,xsequence])

[array([1, 1, 1, 2, 2, 2, 3, 3, 3]), [array([1, 2, 3]), array([1, 2, 3]), array([1, 2, 3])]]


In [143]:
a=[1,2,3,4,5]
b=[4,5,6,7,8,9]
ab=np.unique(a+b)
ab37=[]
for i in range(len(ab)):
    if int(ab[i])>3 and int(ab[i])<7:
        ab37.append(ab[i])
print([ab])
print([ab37])
ab37sum=np.sum(ab37)
print(ab37sum)

[array([1, 2, 3, 4, 5, 6, 7, 8, 9])]
[[4, 5, 6]]
15
